using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlalApi.Authentication
{
    public class Constants
    {
        public const string EC_InternalServerError = "OL1000";
        public const string EC_ObjectReferenceNull = "OL1001";
        public const string EC_DeviceIDRequired = "OL1002";
        public const string EC_InvalidApiKey = "OL1003";
        public const string EC_InvalidUserCredentials = "OL1004";
        public const string EC_UserNotRegistered = "OL1005";
        public const string EC_EmailNotFoundInRequestUser = "OL1006";
        public const string EC_EmailNotRegistered = "OL1007";
        public const string EC_InvalidUserId = "OL1008";
        public const string EC_OldPasswordWrong = "OL1009";
        public const string EC_ValidationFailed = "OL1010";
        public const string EC_UserWithoutDonor = "OL1011";
        public const string EC_BranchNotFound = "OL1012";
        public const string EC_DonorNotFound = "OL1013";
        public const string EC_WrongCharityOfDonor = "OL1014";
        public const string EC_CharityNotFound = "OL1015";
        public const string EC_StripeCharityNotAssociate = "OL1016";
        public const string EC_StripeUserNotAssociate = "OL1017";
        public const string EC_StripeNoCardDetail = "OL1018";
        public const string EC_StripePaymentUnsuccess = "OL1019";
        public const string EC_StripeApiError = "OL1020";
        public const string EC_UserDonorNotBelong = "OL1021";
        public const string EC_InvalidBranchWithCharity = "OL1022";
        public const string EC_DonationNotFoundWithFilters = "OL1023";
        public const string EC_BranchNotFoundWithCharity = "OL1024";
        public const string EC_LicenceExpired = "OL1025";
        public const string EC_BrainTreeGateWayFailed = "OL1026";
        public const string EC_BrainTreePaymentFailed = "OL1027";
        public const string EC_BranchDefaultContactPersonNotFound = "OL1028";
        public const string EC_DCUserAlreadyExist = "OL1029";
        public const string EC_DCUserNotExist = "OL1030";
        public const string EC_DCUserAlreadyLogin = "OL1031";
        public const string EC_ContactLessAuthorisationFailed = "OL1032";
        public const string EC_ContactLessNoTerminal = "OL1033";
        public const string EC_ContactLessNoDonations = "OL1034";
        public const string EC_CharityBrainTreeNotFound = "OL1035";
        public const string EC_BrainTreeCustomerFailed = "OL1036";
        public const string EC_ContactLessAlreadyLinked = "OL1037";
        public const string EC_ContactLessAlreadyLinkedAnotherDonor = "OL1038";
        public const string EC_NoKeyDetail = "OL1039";
        public const string EC_InValidKeyDetails = "OL1040";
        public const string EC_BranchesNotFound = "OL1041";
        public const string EC_PurposesNotFound = "OL1042";
        public const string EC_PurposeNotFound = "OL1043";
        public const string EC_BranchIdNotAuthorized = "OL1044";
        public const string EC_PurposeIdNotAuthorized = "OL1044";
        public const string EC_InvalidPersonWithBranch = "OL1045";
        public const string EC_ForenameIsNull = "OL1046";
        public const string EC_SurnameIsNull = "OL1047";
        public const string EC_EmailIsNull = "OL1048";
        public const string EC_InvalidDonationAmount = "OL1049";
        public const string EC_InvalidPurpose = "OL1050";
        public const string EC_InvalidEmail = "OL1051";
        public const string EC_CharityNameAlreadyExist = "OL1052";
        public const string EC_ExceedLicenceLimit = "OL1053";
        public const string EC_InvalidExternalID = "OL1054";
        public const string EC_ExternalIDNotFound = "OL1055";
        public const string EC_ExternalIDNotAccessible = "OL1056";
        public const string EC_AppIsNotActive = "OL1057";
        public const string EC_PurposeListNotAccessible = "OL1058";
        public const string EC_DonationSaveNotAccessible = "OL1059";
        public const string EC_CharityNameIsExist = "OL1060";
        public const string EC_CharityNameIsNull = "OL1061";
        public const string EC_UserNameIsNull = "OL1062";
        public const string EC_HMRCReferenceIsNull = "OL1063";
        public const string EC_SignatoryTitleIsNull = "OL1064";
        public const string EC_SignatoryForenameIsNull = "OL1065";
        public const string EC_SignatorySurnameIsNull = "OL1066";
        public const string EC_SignatoryAddressIsNull = "OL1067";
        public const string EC_SignatoryPostcodeIsNull = "OL1068";
        public const string EC_SignatoryEmailIsNull = "OL1069";
        public const string EC_UserNameAlreadyExist = "OL1070";
        public const string EC_ExceedLicenceLimitBranch = "OL1071";
        public const string EC_BranchNameIsExist = "OL1072";
        public const string EC_BranchListNotAccessible = "OL1073";
        public const string EC_InvalidBranchExternalId = "OL1074";
        public const string EC_PreventAppAccess = "OL1075";
        public const string EC_PreventCreateCharity = "OL1076";
        public const string EC_PreventCreateBranch = "OL1077";
        public const string EC_BranchNameIsNull = "OL1078";
        public const string EC_HMRCReferenceLengthExceed = "OL1079";
        public const string EC_CharityExternalIdIsNull = "OL1080";
        public const string EC_InvalidCharityExternalId = "OL1081";
    }
}